// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nativedwebhosting/nativedwebhosting/file_meta_data.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FileMetaData struct {
	Hash     string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size_    string   `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Encoding string   `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding,omitempty"`
	TxnHash  []string `protobuf:"bytes,4,rep,name=txnHash,proto3" json:"txnHash,omitempty"`
}

func (m *FileMetaData) Reset()         { *m = FileMetaData{} }
func (m *FileMetaData) String() string { return proto.CompactTextString(m) }
func (*FileMetaData) ProtoMessage()    {}
func (*FileMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_11efa6b62880f238, []int{0}
}
func (m *FileMetaData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FileMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FileMetaData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FileMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetaData.Merge(m, src)
}
func (m *FileMetaData) XXX_Size() int {
	return m.Size()
}
func (m *FileMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetaData proto.InternalMessageInfo

func (m *FileMetaData) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *FileMetaData) GetSize_() string {
	if m != nil {
		return m.Size_
	}
	return ""
}

func (m *FileMetaData) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *FileMetaData) GetTxnHash() []string {
	if m != nil {
		return m.TxnHash
	}
	return nil
}

func init() {
	proto.RegisterType((*FileMetaData)(nil), "nativedwebhosting.nativedwebhosting.FileMetaData")
}

func init() {
	proto.RegisterFile("nativedwebhosting/nativedwebhosting/file_meta_data.proto", fileDescriptor_11efa6b62880f238)
}

var fileDescriptor_11efa6b62880f238 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0xc8, 0x4b, 0x2c, 0xc9,
	0x2c, 0x4b, 0x4d, 0x29, 0x4f, 0x4d, 0xca, 0xc8, 0x2f, 0x2e, 0xc9, 0xcc, 0x4b, 0xd7, 0xc7, 0x14,
	0x49, 0xcb, 0xcc, 0x49, 0x8d, 0xcf, 0x4d, 0x2d, 0x49, 0x8c, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0xc6, 0x50, 0xa7, 0x87, 0x21, 0xa2, 0x94, 0xc3, 0xc5, 0xe3,
	0x96, 0x99, 0x93, 0xea, 0x9b, 0x5a, 0x92, 0xe8, 0x92, 0x58, 0x92, 0x28, 0x24, 0xc4, 0xc5, 0x92,
	0x91, 0x58, 0x9c, 0x21, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x83, 0xc4, 0x8a, 0x33,
	0xab, 0x52, 0x25, 0x98, 0x20, 0x62, 0x20, 0xb6, 0x90, 0x14, 0x17, 0x47, 0x6a, 0x5e, 0x72, 0x7e,
	0x4a, 0x66, 0x5e, 0xba, 0x04, 0x33, 0x58, 0x1c, 0xce, 0x17, 0x92, 0xe0, 0x62, 0x2f, 0xa9, 0xc8,
	0xf3, 0x00, 0x19, 0xc3, 0xa2, 0xc0, 0xac, 0xc1, 0x19, 0x04, 0xe3, 0x3a, 0xc5, 0x9d, 0x78, 0x24,
	0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78,
	0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x4b, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e,
	0x72, 0x7e, 0xae, 0x7e, 0x62, 0x41, 0x7e, 0x7e, 0x51, 0x99, 0xae, 0x91, 0x91, 0x81, 0x89, 0xbe,
	0x1f, 0xd8, 0xc5, 0xba, 0x2e, 0xe1, 0xa9, 0x49, 0xba, 0x1e, 0x50, 0xdf, 0x56, 0x60, 0x09, 0x81,
	0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0xb0, 0xcf, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0x67, 0xa1, 0xe9, 0x35, 0x01, 0x00, 0x00,
}

func (m *FileMetaData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FileMetaData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FileMetaData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxnHash) > 0 {
		for iNdEx := len(m.TxnHash) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TxnHash[iNdEx])
			copy(dAtA[i:], m.TxnHash[iNdEx])
			i = encodeVarintFileMetaData(dAtA, i, uint64(len(m.TxnHash[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Encoding) > 0 {
		i -= len(m.Encoding)
		copy(dAtA[i:], m.Encoding)
		i = encodeVarintFileMetaData(dAtA, i, uint64(len(m.Encoding)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Size_) > 0 {
		i -= len(m.Size_)
		copy(dAtA[i:], m.Size_)
		i = encodeVarintFileMetaData(dAtA, i, uint64(len(m.Size_)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintFileMetaData(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFileMetaData(dAtA []byte, offset int, v uint64) int {
	offset -= sovFileMetaData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FileMetaData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovFileMetaData(uint64(l))
	}
	l = len(m.Size_)
	if l > 0 {
		n += 1 + l + sovFileMetaData(uint64(l))
	}
	l = len(m.Encoding)
	if l > 0 {
		n += 1 + l + sovFileMetaData(uint64(l))
	}
	if len(m.TxnHash) > 0 {
		for _, s := range m.TxnHash {
			l = len(s)
			n += 1 + l + sovFileMetaData(uint64(l))
		}
	}
	return n
}

func sovFileMetaData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFileMetaData(x uint64) (n int) {
	return sovFileMetaData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FileMetaData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFileMetaData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FileMetaData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FileMetaData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMetaData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMetaData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMetaData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMetaData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMetaData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMetaData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Size_ = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Encoding", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMetaData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMetaData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMetaData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Encoding = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxnHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFileMetaData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFileMetaData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFileMetaData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxnHash = append(m.TxnHash, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFileMetaData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFileMetaData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFileMetaData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFileMetaData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFileMetaData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFileMetaData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFileMetaData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFileMetaData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFileMetaData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFileMetaData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFileMetaData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFileMetaData = fmt.Errorf("proto: unexpected end of group")
)
